name: Auto Sync and FTP Deploy

on:
  push:
    branches:
      - main  # Herhangi bir dosya güncellendiğinde (push) otomatik çalışır
  schedule:
    - cron: '0 0 * * *' # Günde bir kez gece yarısı otomatik kontrol eder
  workflow_dispatch: # Hala manuel çalıştırma butonunu korur

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🔍 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_SYNC_TOKEN }}

      - name: 🔄 Sync From Upstream
        env:
          MY_TOKEN: ${{ secrets.MY_SYNC_TOKEN }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git remote remove upstream || true
          git remote add upstream https://github.com/raciplak/php-charm-studio.git
          
          git fetch upstream main
          git checkout main
          git reset --hard upstream/main
          
          git push "https://x-access-token:${MY_TOKEN}@github.com/${{ github.repository }}.git" main --force

      - name: 🚀 FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./public_html/eticaret/php-charm-studio-main/
          exclude: |
            **/.git*
            **/.git/**
            **/.github/**
            **/node_modules/**
            .ftp-deploy-sync-state.json
